# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.cache/wt} [current_project]
set_property parent.project_path {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/ALUbasic.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/ControlCodeGenerator3.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/Temp/OperandDecode2.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/ControlCodeGenerator1Async.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/new/IO_Module.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/StackPointer.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/RegisterFlags.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/IR.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/ControlCodeGenerator4.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/ControlCodeGenerator2.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/Buffer3.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/Buffer1.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/Bubble.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/Temp/RegisterArr.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/Temp/pc.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/Temp/as2.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/Temp/as1.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/Temp/3PortMem.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/WBModule.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/OperandDecode2.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/FlagRegister.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/ConditionalBranch.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/Buffer2.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/imports/files/ALUModule.v}
  {/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/sources_1/imports/sources_1/new/TopModule.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/constrs_1/imports/VHDL/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{/home/abhimanyu/Desktop/BISWAS FINAL/Pipelined Processor before  Mar 23/ANPPV_RISC_Pipelned_Processor.srcs/constrs_1/imports/VHDL/Nexys4_Master.xdc}}]


synth_design -top TopModule -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef TopModule.dcp

catch { report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb }
